/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './index.html',
    './features.html',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "error-dim": "#d7383b",
        "on-error": "#490006",
        "on-primary": "#005762",
        "error": "#ff716c",
        "inverse-on-surface": "#565554",
        "surface": "#0e0e0e",
        "secondary-container": "#6e208c",
        "surface-container": "#1a1919",
        "background": "#0e0e0e",
        "on-secondary": "#4c0068",
        "on-primary-fixed-variant": "#005762",
        "primary-dim": "#00d4ec",
        "primary": "#81ecff",
        "secondary-dim": "#ce7eec",
        "on-secondary-container": "#f1bfff",
        "secondary-fixed": "#f2c1ff",
        "surface-container-high": "#201f1f",
        "on-secondary-fixed": "#580078",
        "on-surface-variant": "#adaaaa",
        "secondary": "#dd8bfb",
        "primary-fixed": "#00e3fd",
        "on-primary-container": "#004d57",
        "tertiary": "#eaffb8",
        "surface-container-lowest": "#000000",
        "surface-variant": "#262626",
        "surface-dim": "#0e0e0e",
        "surface-container-highest": "#262626",
        "outline": "#777575",
        "surface-container-low": "#131313",
        "on-surface": "#ffffff",
        "inverse-surface": "#fcf8f8",
        "on-tertiary-container": "#445d00",
        "on-tertiary-fixed-variant": "#4c6800",
        "on-tertiary": "#4b6600",
        "on-secondary-fixed-variant": "#792c97",
        "surface-tint": "#81ecff",
        "tertiary-fixed": "#befc00",
        "primary-fixed-dim": "#00d4ec",
        "outline-variant": "#494847",
        "tertiary-dim": "#b2ed00",
        "on-tertiary-fixed": "#354900",
        "on-background": "#ffffff",
        "inverse-primary": "#006976",
        "tertiary-container": "#befc00",
        "on-error-container": "#ffa8a3",
        "secondary-fixed-dim": "#ebadff",
        "error-container": "#9f0519",
        "tertiary-fixed-dim": "#b2ed00",
        "on-primary-fixed": "#003840",
        "primary-container": "#00e3fd",
        "surface-bright": "#2c2c2c"
      },
      fontFamily: {
        "headline": ["Orbitron", "Space Grotesk"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px"
      },
      animation: {
        spotlight: "spotlight 2s ease .75s 1 forwards",
      },
      keyframes: {
        spotlight: {
          "0%": {
            opacity: 0,
            transform: "translate(-72%, -62%) scale(0.5)",
          },
          "100%": {
            opacity: 1,
            transform: "translate(-50%,-40%) scale(1)",
          },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
